### PR TITLE
feat (nexus-web): fixed light theme issue 

### LINKED ISSUE #563: ID Page
Image

-remove dark values

### PR DESCRIPTION
**Pull request by Zanti00**
**Related Issue**
Closes #563 

**Summary**

- Updated the GDG ID section to use a static dark theme for aesthetic consistency.

**Strategies**

- Forced dark background (#0F0E0E) on IdSection.
- Overrode CSS variables (--background, --foreground) to ensure light-mode compatibility for text and child components from @packages/spark-ui.

**Additional Information**

- Verified contrast across interactive elements (Blobs, Beams, HeroStage, etc.).

### CODE REVIEW

**Comment by Zanti00** [comment]
image

**Review by r0undy — CHANGES_REQUESTED** [review]
Rather than editing the css in-line, try to just edit the global.css para damay na lahat ng pages.

I suggest to just edit the `--background` value in global.css into `#0F0E0E`

**Comment by Zanti00** [comment]
> Rather than editing the css in-line, try to just edit the global.css para damay na lahat ng pages.
> 
> I suggest to just edit the `--background` value in global.css into `#0F0E0E`

should I also change the foreground color from #0F0E0E to something white e.g. five f's? also what you're talking about --background is it the one in the :root?

**Comment by r0undy** [comment]
yes, yung nasa root. both foreground at background gawin mo na dark para always dark na sya on all pages

File: apps/nexus-web/src/features/id/components/IdSection.tsx [hunk 1]
```diff
@@ -10,29 +10,39 @@ export function IdSection() {
   return (
     <div
       className="relative overflow-x-hidden min-h-screen pt-24 md:pt-44 lg:pt-60 pb-48 px-4 md:px-8 lg:px-16"
-      style={{
-        backgroundColor: "#0F0E0E",
-        "--background": "#0F0E0E",
-        "--foreground": "#ededed",
-      } as React.CSSProperties}
+      style={
```
Comment (r0undy) [inline apps/nexus-web/src/features/id/components/IdSection.tsx]: remove mo na lang si `style`, className lang dapat attribute ni div

**Review by r0undy — CHANGES_REQUESTED** [review]

**Review by r0undy — APPROVED** [review]
nice! lgtm! good job
