### PR TITLE
feat(nexus-web): fixed AboutSection component dark theme and max-width values

### LINKED ISSUE #557: Revise About Page
- Remove dark values
- no max width
Image

### PR DESCRIPTION
**Pull request by Zanti00**
Closes #557 

**Summary**
This PR forces a static dark theme and aligns the layout/responsiveness of the AboutSection component with the TeamSection pattern. It also fixes the scaling and positioning of the spiral decoration to ensure it remains correctly anchored to the video across all device sizes.

**Strategies**

- Static Dark Theme: Implemented an inline style={{ backgroundColor: "rgba(15, 14, 14, 1)" }} and forced the dark class on the root container.
- Layout Alignment: Standardized the content width using maxWidth="7xl" and padding="lg" within the root <Container>.
- Responsive Spacing: Replaced fixed internal margins (like lg:mx-35) with responsive root padding (px-4 md:px-8 lg:px-16).
- Spiral Scaling & Anchoring:
- - Capped the spiral width using min(1800px, 100vw) to prevent blowout on zoom-out.
- - Relocated the spiral inside the video's FadeInSection to anchor it to the video container.
- - Positioned the spiral relative to the video's bottom (top: 90%) to ensure it "holds" the video consistently on mobile, tablet, and PC.
- Video Visibility: Fixed a layout collapse by explicitly setting w-full on the video Box, ensuring the aspect-video ratio calculates correctly within the new flex wrapper.

**Additional Information**

- Verified layout consistency with TeamSection.tsx on desktop, tablet, and mobile.
- Confirmed that the spiral decoration stays "stuck" to the video and doesn't overlap section text.
- All existing tests pass.

### CODE REVIEW

**Comment by Zanti00** [comment]
image
image

File: apps/nexus-web/src/features/about/components/AboutSection.tsx [hunk 1]
```diff
@@ -31,7 +31,10 @@ const FadeInSection = ({
 
 export function AboutSection() {
   return (
-    <div className="relative overflow-x-hidden pt-60 pb-48 px-0">
+    <div
+      className="relative overflow-x-hidden pt-60 pb-48 px-4 md:px-8 lg:px-16 text-[#ededed] dark [--background:#0F0E0E] [--foreground:#ededed]"
+      style={{ backgroundColor: "rgba(15, 14, 14, 1)" }}
```
Comment (r0undy) [inline apps/nexus-web/src/features/about/components/AboutSection.tsx]: pa-remove na lang 'tong inline style if na-apply mo na 'yong `#0F0E0E` value sa global.css from your other PR

**Review by r0undy — CHANGES_REQUESTED** [review]
almost there!

File: apps/nexus-web/src/features/about/components/AboutSection.tsx (hunk 1 above)
Comment (Zanti00) [reply apps/nexus-web/src/features/about/components/AboutSection.tsx]: yes po edit ko lang din

File: apps/nexus-web/src/features/about/components/AboutSection.tsx [hunk 2]
```diff
@@ -32,8 +32,8 @@ const FadeInSection = ({
 export function AboutSection() {
   return (
     <div
-      className="relative overflow-x-hidden pt-60 pb-48 px-4 md:px-8 lg:px-16 text-[#ededed] dark [--background:#0F0E0E] [--foreground:#ededed]"
-      style={{ backgroundColor: "rgba(15, 14, 14, 1)" }}
+      className="relative overflow-x-hidden pt-60 pb-48 px-4 md:px-8 lg:px-16"
+      style={{ backgroundColor: "var(--background)" }}
```
Comment (r0undy) [inline apps/nexus-web/src/features/about/components/AboutSection.tsx]: same lang from last time, no need na si style attribute. just classname would suffice

**Review by r0undy — CHANGES_REQUESTED** [review]

**Review by r0undy — APPROVED** [review]
lgtm! nice
